steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  -'gcloud'
  - 'functions'
  - 'deploy'
  - 'robo-de-noticias-IA' #nomeda nossa Cloud Function 
  - '--gen2' # Usa a 2 geração de Functions, mais moderna
  - '--region=southamerica-east1' # Região de são Paulo
  - '--runtime=python311' # Versão do Python
  - '--source=.'
  - '--entry-point=executar_robo' # Nome da função em main.py
  - '--trigger-topic=run-daily-job' # Será acionada por este tópico Pub/Sub
  # Permite que a função acesse o Secret Manager
  - '--service-account=499414425820-compute@developer.gserviceaccount.com'
